package gui;

public enum Metrics {
	
	VERTEXINDEGREE,
	VERTEXOUTDEGREE,
	VERTEXDEGREE,
	VERTEXBETWEENNESS,
	EDGEBETWEENNESS,
	GRAPHDIAMETER,
	NUMBEROFVERTICES,
	NUMBEROFEDGES,
	NUMBEROFCONNECTEDCOMPONENTS

}
